# Generated by Django 4.0 on 2024-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_currency', models.CharField(max_length=255, verbose_name='Отдаёте при обмене')),
                ('get_currency', models.CharField(max_length=255, verbose_name='Получаете при обмене')),
                ('telegram', models.CharField(max_length=255, verbose_name='Телеграм')),
            ],
        ),
    ]
