# Generated by Django 5.0.8 on 2024-08-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestform',
            options={'verbose_name': 'Заявку с формы', 'verbose_name_plural': 'Заявки с формы'},
        ),
    ]
